### ISSUE TITLE
x11-wm/awesome-3.5.8 incompatibilty

### ISSUE THREAD

**Issue by landscape69** [Elv13/awesome-configs#25]
its incomtabble with latest awesome-3.5.8 . it would be nice if u can also fix this

**Comment by Elv13** [comment]
I will take a look. I am hard to work on the next version (for Awesome 3.6). I am sending a lot of patches upstream right now, so I can't really push the new version as it literally work with no version of Awesome at all.

**Comment by landscape69** [comment]
thanks you very much, if u send them patches maybe ask if your great work also can also be official a part of awesome wm. its worth :)

**Comment by Elv13** [comment]
>  if u send them

I am an Awesome co-maintainer, so "them" also include me ;).

> if your great work also can also be official a part of awesome wm. its worth :)

That would drive most current user crazy. I am not trying to bloat Awesome. I just move features when they have no impact on the current users. Also, I can only do it just before a major release because I want my config to run on the stable branch, so this is time before the freeze.

I am mostly done merging the "shape" API that allow the fancy themes. The "pattern" and "pixmap" ones will follow soon. I also merge the layout declaration system, mostly restoring features lost from 3.4->3.5 widget system rewrite. Finally, I am merging tabbing and dynamic client layout system. My 3.4 config had it, it was lost in 3.5 and will be back in 3.6. Other possible features going upstream include the async API and the object property extension API. So, beside the first one, nothing really "user visible", but it will be easier to build configs like mine without having to write 20000 lines of utilities, libraries and extensions like my config does.

**Comment by landscape69** [comment]
well

**Comment by landscape69** [comment]
i propose following if u intended to make a integration in to awesome:

1) remove all things which have depencies with  online services: f.e. : weather  or additional widgets. concentrate on your great theme and shortcuts, which improve awesome so much.

i really like the way u handle shortcuts for apps. the app tile layout  and the startup info widget for commands are really cool and i wish it could be available and support in main awesome. its no bloating of awesome. its a good way to make user all time reminds of awesome individual preconfigured shortcuts.

**Comment by Elv13** [comment]
> widget for commands

This is already upstream since a few months. It is a new implementation by (mostly) Actionless and (some of it) me. We both had implemented a shortcut widget like mine, so we took the best of both.

> weather or additional widgets. concentrate on your great theme and shortcuts, which improve awesome so much.

That's the drawer module, I don't care about it much, but some other users do. It is maintained by AxelTB, it is not going upstream.

> the app tile layout 

It pull to much code along with it to go upstream.

**Comment by Elv13** [comment]
Can you share the error you have. I just installed the 3.5.8 Gentoo package and everything seem normal.

**Comment by landscape69** [comment]
i am using gentoo too. i have no clue what have been changed but with the latest pull from git i got it working too.

small problem ist with the \drawer\dateinfo.lua:59 it dont show up the calender

**Comment by Elv13** [comment]
The 2016 version is now available
