### ISSUE TITLE
i have request for calendar and a conky script on screen

### ISSUE THREAD

**Issue by landscape69** [Elv13/awesome-configs#29]
please see screen shot

http://pix.toile-libre.org/upload/original/1472295863.png

**Comment by Elv13** [comment]
Hello. My 3.4 config less or more had this. It has some issues. 

* First, Awesome is single threaded, so eventually, adding too much visible stuff makes it very slow.
* Knowing is the desktop is visible is very hard. It requires path finding and isn't supported by Awesome
 * I am no longer the developer of this popup. @actionless has a new (better) implementation and it has been merged into Awesome itself. Adding custom widgets is planned-ish, but currently not supported.

For now, here's something you can play with
https://github.com/Elv13/awesome-configs/commit/9ed39434f057fcfcb3ae42fe7e3cef98d36f05a4

It is **very** experimental and requires custom Awesome patches. Most old features are back, the code is mostly new. It will have its own set of bugs and regressions. However, I will actually fix those rather than ignore them like the 3.5 branch. So, if you upgrade, feel free to report bugs. I will fix those (really). The 3.5 edition of my config wont get any additional fixes or features.

I close this and suggest you re-submit on Awesome issue tracker itself. Note that my 3.6 config still show the old shortcut popup for now, but I will transition to the new one eventually. My old implementation wont get new features as it is phased out.
