### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by jhamfler** [Elv13/awesome-configs#36]
Error after cloning and replacing existing .config/awesome
```
...tyrannical/init.lua:379 in main chunk
[C]: in function 'require'
...rc.lua:28: in main chunk
error: ... tyrannical/ ... attempt to call nil value (field 'add_rule_source')
```

awesome --version
```
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2
```

cloning tyrannical manually doesn't help

**Comment by Elv13** [comment]
Hello,

My config uses the experimental version of AwesomeWM. It requires the `doc_tests_and_notif` branch of my fork. This branch merges some unfinished and experimental pull requests that are not part of AwesomeWM yet. I stopped supporting my config using the vanilla version of Awesome since v4.0 was released since it was slowing the progress of getting my features into the upstream version.

If you want a specific feature of my config, they are available as modules and support AwesomeWM 3.5 to 4.3 (sometime using different releases).
